//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BABWebApp.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtSub
    {
        public int SubmissionId { get; set; }
        public string Image { get; set; }
        public string ArtistId { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string ValueAddress { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
