//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BABWebApp.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BowlAfterBowlEntities : DbContext
    {
        public BowlAfterBowlEntities()
            : base("name=BowlAfterBowlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArtSub> ArtSubs { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ClipSub> ClipSubs { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Episode> Episodes { get; set; }
        public virtual DbSet<Podcast> Podcasts { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Soundbite> Soundbites { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
    }
}
