//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BABWebApp.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Episode()
        {
            this.Donations = new HashSet<Donation>();
            this.Chapters = new HashSet<Chapter>();
            this.Soundbites = new HashSet<Soundbite>();
        }
    
        public int EpisodeId { get; set; }
        public string Title { get; set; }
        public int PodcastId { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public System.DateTime Published { get; set; }
        public string Author { get; set; }
        public string Artwork { get; set; }
        public short EpisodeNumber { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string AudioFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapter> Chapters { get; set; }
        public virtual Podcast Podcast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soundbite> Soundbites { get; set; }
    }
}
