//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BABWebApp.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podcast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podcast()
        {
            this.Episodes = new HashSet<Episode>();
        }
    
        public int PodcastId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public string Docs { get; set; }
        public string Language { get; set; }
        public System.DateTime Published { get; set; }
        public string ManagingEditor { get; set; }
        public string WebMaster { get; set; }
        public bool IsLocked { get; set; }
        public string Funding { get; set; }
        public string ItunesAuthor { get; set; }
        public bool IsExplicit { get; set; }
        public Nullable<int> ItunesTypeId { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episode> Episodes { get; set; }
    }
}
