//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BABWebApp.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soundbite
    {
        public int SoundbiteId { get; set; }
        public int EpisodeId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ProducerId { get; set; }
    
        public virtual Episode Episode { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
